// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_the_great_hundred = "CgkI7_LWy9QOEAIQBg"; // <GPGSID>
        public const string achievement_boo = "CgkI7_LWy9QOEAIQCQ"; // <GPGSID>
        public const string achievement_grand_ol_minute = "CgkI7_LWy9QOEAIQBA"; // <GPGSID>
        public const string achievement_get_the_boot = "CgkI7_LWy9QOEAIQCg"; // <GPGSID>
        public const string achievement_participation_trophy = "CgkI7_LWy9QOEAIQAg"; // <GPGSID>
        public const string achievement_180_your_way_out_of_the_hooks_way = "CgkI7_LWy9QOEAIQBw"; // <GPGSID>
        public const string leaderboard_swimmin_time = "CgkI7_LWy9QOEAIQAQ"; // <GPGSID>
        public const string achievement_shark_tale = "CgkI7_LWy9QOEAIQCw"; // <GPGSID>
        public const string achievement_maybe_you_should_take_a_break = "CgkI7_LWy9QOEAIQCA"; // <GPGSID>
        public const string achievement_back_to_class = "CgkI7_LWy9QOEAIQDA"; // <GPGSID>
        public const string achievement_playing_right = "CgkI7_LWy9QOEAIQBQ"; // <GPGSID>
        public const string achievement_the_more_the_merrier = "CgkI7_LWy9QOEAIQAw"; // <GPGSID>

}

